name: Backend - Build & Deploy to Docker Hub

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # Build và Publish từng service
    - name: Build & Publish OrderService
      run: |
        dotnet build ./OrderService/OrderService.csproj
        dotnet publish ./OrderService/OrderService.csproj -c Release -o ./publish/OrderService

    - name: Build & Publish ProductService
      run: |
        dotnet build ./ProductService/ProductService.csproj
        dotnet publish ./ProductService/ProductService.csproj -c Release -o ./publish/ProductService

    - name: Build & Publish InventoryService
      run: |
        dotnet build ./InventoryService/InventoryService.csproj
        dotnet publish ./InventoryService/InventoryService.csproj -c Release -o ./publish/InventoryService

    - name: Build & Publish UserService
      run: |
        dotnet build ./UserService/UserService.csproj
        dotnet publish ./UserService/UserService.csproj -c Release -o ./publish/UserService

    # Login Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build và push Docker image từng service
    - name: Build & Push OrderService image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/order-service ./OrderService
        docker push ${{ secrets.DOCKER_USERNAME }}/order-service

    - name: Build & Push ProductService image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/product-service ./ProductService
        docker push ${{ secrets.DOCKER_USERNAME }}/product-service

    - name: Build & Push InventoryService image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/inventory-service ./InventoryService
        docker push ${{ secrets.DOCKER_USERNAME }}/inventory-service

    - name: Build & Push UserService image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service ./UserService
        docker push ${{ secrets.DOCKER_USERNAME }}/user-service
