name: Backend - Build & Deploy to Docker Hub

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build project
      run: dotnet build ./SmartOrderHub.sln

    - name: Publish project
      run: dotnet publish ./SmartOrderHub/SmartOrderHub.csproj -c Release -o ./publish

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/smartorder-backend ./backend

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/smartorder-backend
